import { ArrowRight, BookOpen, Building2, GraduationCap, Menu, Microscope, Quote, Sparkles, Users, X } from 'lucide-react'
import { Link, NavLink, Route, Routes, useLocation } from 'react-router-dom'
import { useEffect, useState } from 'react'

const nav=[['Approach','/approach'],['Community','/community'],['Professional','/professional'],['Research','/research'],['Testimonials','/testimonials'],['Team','/team']]
const E=({children})=><div className="eyebrow">{children}</div>
const Page=({label,title,intro,children})=><main className="page"><section className="page-hero"><div className="wrap"><E>{label}</E><h1>{title}</h1><p>{intro}</p></div></section>{children}</main>
const Wrap=({children,className=''})=><div className={'wrap '+className}>{children}</div>
const Card=({children})=><article className="card">{children}</article>

function Layout({children}){
 const [open,setOpen]=useState(false); const {pathname}=useLocation()
 useEffect(()=>{window.scrollTo(0,0);setOpen(false)},[pathname])
 return <div className="site"><header><div className="wrap nav"><Link to="/" className="brand"><span>S</span><div><b>Samyak Dhyaan Sangha</b><small>SDS · Healthy Mind Initiatives</small></div></Link><nav>{nav.map(([n,p])=><NavLink key={p} to={p}>{n}</NavLink>)}<Link className="nav-cta" to="/contact">Explore programs</Link></nav><button className="menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div>{open&&<div className="mobile">{nav.map(([n,p])=><Link key={p} to={p}>{n}</Link>)}<Link to="/contact">Contact</Link></div>}</header>{children}<footer><Wrap className="footer"><div>© {new Date().getFullYear()} Samyak Dhyaan Sangha</div><div><a href="https://youtube.com/@quarkwellbeing" target="_blank">Quark Wellbeing</a><a href="https://youtube.com/@darshan-quest" target="_blank">Darshan Quest</a><a href="https://quarkwellbeing.substack.com/" target="_blank">Blog</a></div></Wrap></footer></div>
}

function Home(){return <main><section className="home-hero"><div className="orb a"/><div className="orb b"/><Wrap className="hero-grid"><div><span className="pill"><Sparkles size={14}/> Towards an Indian science of mental wellbeing</span><h1>Understand the mind.<br/><i>Cultivate it for life.</i></h1><p>A living approach to mental wellbeing bringing India’s traditions of Sāṃkhya, Yoga and Upāsanā into dialogue with contemporary research, learning and everyday practice.</p><div className="actions"><Link className="primary" to="/community">Explore community <ArrowRight size={17}/></Link><Link className="secondary" to="/professional">Healthy Mind Initiatives</Link></div></div><div className="pathways"><E>One vision · two pathways</E><h2>Mental fitness as part of everyday life.</h2><Link to="/community" className="path green"><Users/><small>Community</small><b>Samyak Dhyaan Sangha</b><p>Practice, learning and a community for people cultivating a healthy mind.</p></Link><Link to="/professional" className="path sand"><Building2/><small>Professional</small><b>Healthy Mind Initiatives</b><p>Programs for individuals, institutions, teams and leaders.</p></Link></div></Wrap></section><section className="dark"><Wrap className="split"><div><E>Why this work, why now</E><h2>Begin before something goes wrong.</h2></div><div><p>Mental wellbeing is often approached reactively. SDS begins earlier: understanding how the mind functions and how it can be developed through regular practice.</p><Link className="text-link" to="/approach">Explore our approach <ArrowRight size={16}/></Link></div></Wrap></section><section className="section"><Wrap><E>Explore SDS</E><h2 className="section-title">One website. A connected body of work.</h2><div className="grid3"><Card><BookOpen/><h3>Community</h3><p>Sandhyā, Patanjal Upasana, fellowship and practitioner learning.</p><Link to="/community">Visit community →</Link></Card><Card><Building2/><h3>Professional</h3><p>Mental-fitness pathways for organizations, institutions and individuals.</p><Link to="/professional">View programs →</Link></Card><Card><Microscope/><h3>Research</h3><p>Inquiry at the meeting point of Sāṃkhya, Yoga, cognition and wellbeing.</p><Link to="/research">Explore research →</Link></Card></div></Wrap></section></main>}

function Approach(){return <Page label="Our approach" title="A developmental approach to the mind." intro="Rather than waiting for distress, SDS focuses on understanding and cultivating the mind through sustained practice, inquiry and learning."><section className="section"><Wrap className="split"><div><h2 className="section-title">Two knowledge streams, in dialogue.</h2></div><div className="prose"><p>India’s knowledge traditions—especially Sāṃkhya, Yoga and Vedic thought—offer systematic inquiry into mind, self, action and human flourishing.</p><p>SDS brings these traditions into conversation with contemporary psychology, psychiatry, neuroscience and technology, without treating either stream as a substitute for the other.</p></div></Wrap></section></Page>}

function Community(){return <Page label="Community division" title="Samyak Dhyaan Sangha" intro="Built for practitioners — connect with people cultivating a healthy mind through practice, study and community."><section className="section"><Wrap><div className="grid3">{[['Sandhyā','A living cultural practice for cultivating a healthy mind and balanced life.'],['Patanjal Upasana','An accessible practice shaped around a structural understanding of the mind.'],['Sāṃkhya–Yoga Fellowship','Weekly study and inquiry into Sāṃkhya and Yogadarśana.']].map(([a,b])=><Card key={a}><BookOpen/><h3>{a}</h3><p>{b}</p></Card>)}</div></Wrap></section></Page>}

function Professional(){return <Page label="Healthy Mind Initiatives" title={<>Build a stronger mind. <i>Live a fuller life.</i></>} intro="Professional outreach for individuals, institutions, teams and leaders, grounded in the same framework of mental cultivation."><section className="section sand-bg"><Wrap><div className="grid3">{[['Organizations','Custom training for teams, leadership and high-performance roles.'],['Institutions','Structured attention and mental-development modules for students and educators.'],['Individuals','Personal programs for focus, clarity and greater mental control.']].map(([a,b],i)=><Card key={a}>{i===0?<Building2/>:<GraduationCap/>}<h3>{a}</h3><p>{b}</p><Link to="/contact">Enquire →</Link></Card>)}</div></Wrap></section></Page>}

function Research(){return <Page label="Research & inquiry" title="Tradition, examined with a contemporary lens." intro="Sustained study of Sāṃkhya, Yoga and Vedic thought alongside contemporary questions around cognition, wellbeing and human development."><section className="section"><Wrap><div className="stats"><div><b>30 years</b><span>Research and study informing the conceptual framework.</span></div><div><b>400+</b><span>Participants in a structured five-session Sandhyā series.</span></div><div><b>India · USA · UK</b><span>Fellowship participation described in the source material.</span></div></div><div className="prose wide"><h2>Academic engagement</h2><p>The source document records a paper selected for presentation at Auro University in February 2026, an abstract selected for a conference at Oxford, and a paper on AI and Self submitted for consideration in Paris.</p></div></Wrap></section></Page>}

const testimonials=[
 ['Participant feedback','The source document includes participant-feedback screenshots from SDS programs. We are keeping this section ready for the approved testimonial wording and names rather than inventing quotations.'],
 ['Practice community','Feedback can be grouped here around practice experience, learning clarity and community participation once the original text is supplied or transcribed.'],
 ['Programs & workshops','A second testimonial group can feature workshop and institutional participants, with consented names, roles and photographs where available.']
]
function Testimonials(){return <Page label="Voices from the community" title="Experiences from practice and learning." intro="A dedicated space for participant voices from SDS practices, fellowships, courses and workshops."><section className="section"><Wrap><div className="grid3">{testimonials.map(([a,b])=><Card key={a}><Quote/><h3>{a}</h3><p>{b}</p></Card>)}</div><p className="note">The DOCX contains feedback as images, but does not provide reliable machine-readable testimonial text. Placeholder copy is intentionally used until the approved wording is available.</p></Wrap></section></Page>}

function Team(){return <Page label="People behind the work" title="Team & inspiration" intro="A multidisciplinary effort connecting research, learning design, community development and India’s knowledge traditions."><section className="section"><Wrap><div className="team-grid"><Card><div className="avatar">RM</div><small>Co-founder</small><h3>Raunak Maheshwari</h3><p>Research · Learning Design · Community · Outreach</p></Card><Card><div className="avatar">AA</div><small>CTO</small><h3>Anil Arya</h3><p>Research · Writing · Presenting</p></Card><Card><div className="avatar warm">HC</div><small>Inspiration</small><h3>Dr. Harishchandra</h3><p>The source document describes the work as shaped by his three decades of research. It identifies him as a combustion scientist, Vedic scholar, author, and alumnus of IIT Kanpur and Princeton University.</p></Card></div></Wrap></section></Page>}

function Contact(){return <Page label="Get involved" title="Find the pathway that fits." intro="Join the practitioner community, explore a learning program, or start a conversation about Healthy Mind Initiatives."><section className="section"><Wrap><div className="grid3"><Card><h3>Community</h3><p>Explore practice, learning and fellowship.</p><a href="https://youtube.com/@quarkwellbeing" target="_blank">Explore our work →</a></Card><Card><h3>Organizations</h3><p>Discuss custom training and professional programs.</p><span>Contact details to be added</span></Card><Card><h3>Institutions</h3><p>Explore structured modules for students and educators.</p><span>Contact details to be added</span></Card></div></Wrap></section></Page>}

export default function App(){return <Layout><Routes><Route path="/" element={<Home/>}/><Route path="/approach" element={<Approach/>}/><Route path="/community" element={<Community/>}/><Route path="/professional" element={<Professional/>}/><Route path="/research" element={<Research/>}/><Route path="/testimonials" element={<Testimonials/>}/><Route path="/team" element={<Team/>}/><Route path="/contact" element={<Contact/>}/></Routes></Layout>}
