import { ArrowRight, BookOpen, Building2, GraduationCap, Menu, Microscope, Quote, Sparkles, Users, X } from 'lucide-react'
import { Link, NavLink, Route, Routes, useLocation } from 'react-router-dom'
import { useEffect, useState } from 'react'

const nav=[['Approach','/approach'],['Community','/community'],['Professional','/professional'],['Research','/research'],['Testimonials','/testimonials'],['Team','/team']]
const communityPages=[['About SDS','/community/about'],['Programs','/community/programs'],['Practice','/community/practice'],['Fellowship','/community/fellowship'],['Resources','/community/resources']]
const professionalPages=[['About HMI','/professional/about'],['Programs','/professional/programs'],['Organizations','/professional/organizations'],['Institutions','/professional/institutions'],['Individuals','/professional/individuals']]
const E=({children})=><div className="eyebrow">{children}</div>
const Page=({label,title,intro,children})=><main className="page"><section className="page-hero"><div className="wrap"><E>{label}</E><h1>{title}</h1><p>{intro}</p></div></section>{children}</main>
const Wrap=({children,className=''})=><div className={'wrap '+className}>{children}</div>
const Card=({children})=><article className="card">{children}</article>

function Layout({children}){
 const [open,setOpen]=useState(false); const {pathname}=useLocation()
 useEffect(()=>{window.scrollTo(0,0);setOpen(false)},[pathname])
 return <div className="site"><header><div className="wrap nav"><Link to="/" className="brand"><span>S</span><div><b>Samyak Dhyaan Sangha</b><small>SDS · Healthy Mind Initiatives</small></div></Link><nav>{nav.map(([n,p])=><NavLink key={p} to={p}>{n}</NavLink>)}<Link className="nav-cta" to="/contact">Explore programs</Link></nav><button className="menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div>{open&&<div className="mobile">{nav.map(([n,p])=><Link key={p} to={p}>{n}</Link>)}<Link to="/contact">Contact</Link></div>}</header>{children}<footer><Wrap className="footer"><div>© {new Date().getFullYear()} Samyak Dhyaan Sangha</div><div><a href="https://youtube.com/@quarkwellbeing" target="_blank">Quark Wellbeing</a><a href="https://youtube.com/@darshan-quest" target="_blank">Darshan Quest</a><a href="https://quarkwellbeing.substack.com/" target="_blank">Blog</a></div></Wrap></footer></div>
}

function Home(){return <main><section className="home-hero"><div className="hero-gridlines"/><div className="orb a"/><div className="orb b"/><div className="float-symbol s1">ॐ</div><div className="float-symbol s2">ध्यान</div><div className="float-symbol s3">योग</div><Wrap className="hero-grid"><div className="hero-copy"><span className="pill"><Sparkles size={14}/> Towards an Indian science of mental wellbeing</span><h1>Understand the mind.<br/><i>Cultivate it for life.</i></h1><p>A living approach to mental wellbeing bringing India’s traditions of Sāṃkhya, Yoga and Upāsanā into dialogue with contemporary research, learning and everyday practice.</p><div className="actions"><Link className="primary" to="/community">Explore community <ArrowRight size={17}/></Link><Link className="secondary" to="/professional">Healthy Mind Initiatives</Link></div></div><div className="pathways hero-card"><div className="pulse-ring r1"/><div className="pulse-ring r2"/><E>One vision · two pathways</E><h2>Mental fitness as part of everyday life.</h2><Link to="/community" className="path green"><Users/><small>Community</small><b>Samyak Dhyaan Sangha</b><p>Practice, learning and a community for people cultivating a healthy mind.</p></Link><Link to="/professional" className="path sand"><Building2/><small>Professional</small><b>Healthy Mind Initiatives</b><p>Programs for individuals, institutions, teams and leaders.</p></Link></div></Wrap></section><section className="dark"><Wrap className="split"><div><E>Why this work, why now</E><h2>Begin before something goes wrong.</h2></div><div><p>Mental wellbeing is often approached reactively. SDS begins earlier: understanding how the mind functions and how it can be developed through regular practice.</p><Link className="text-link" to="/approach">Explore our approach <ArrowRight size={16}/></Link></div></Wrap></section><section className="section"><Wrap><E>Explore SDS</E><h2 className="section-title">One website. A connected body of work.</h2><div className="grid3"><Card><BookOpen/><h3>Community</h3><p>Sandhyā, Patanjal Upasana, fellowship and practitioner learning.</p><Link to="/community">Visit community →</Link></Card><Card><Building2/><h3>Professional</h3><p>Mental-fitness pathways for organizations, institutions and individuals.</p><Link to="/professional">View programs →</Link></Card><Card><Microscope/><h3>Research</h3><p>Inquiry at the meeting point of Sāṃkhya, Yoga, cognition and wellbeing.</p><Link to="/research">Explore research →</Link></Card></div></Wrap></section></main>}

function Approach(){return <Page label="Our approach" title="A developmental approach to the mind." intro="Rather than waiting for distress, SDS focuses on understanding and cultivating the mind through sustained practice, inquiry and learning."><section className="section"><Wrap className="split"><div><h2 className="section-title">Two knowledge streams, in dialogue.</h2></div><div className="prose"><p>India’s knowledge traditions—especially Sāṃkhya, Yoga and Vedic thought—offer systematic inquiry into mind, self, action and human flourishing.</p><p>SDS brings these traditions into conversation with contemporary psychology, psychiatry, neuroscience and technology, without treating either stream as a substitute for the other.</p></div></Wrap></section></Page>}

const DivisionNav=({type})=>{const items=type==='community'?communityPages:professionalPages;return <div className={'division-nav '+type}><Wrap><div className="division-nav-inner"><strong>{type==='community'?'Community':'Healthy Mind Initiatives'}</strong>{items.map(([n,p])=><NavLink key={p} to={p}>{n}</NavLink>)}</div></Wrap></div>}
const SubPage=({type,label,title,intro,children})=><><DivisionNav type={type}/><Page label={label} title={title} intro={intro}>{children}</Page></>

function Community(){return <><DivisionNav type="community"/><Page label="Community division" title="Samyak Dhyaan Sangha" intro="Built for practitioners — connect with people cultivating a healthy mind through practice, study and community."><section className="section"><Wrap><div className="grid3">{[['Sandhyā','A living cultural practice for cultivating a healthy mind and balanced life.'],['Patanjal Upasana','An accessible practice shaped around a structural understanding of the mind.'],['Sāṃkhya–Yoga Fellowship','Weekly study and inquiry into Sāṃkhya and Yogadarśana.']].map(([a,b])=><Card key={a}><BookOpen/><h3>{a}</h3><p>{b}</p></Card>)}</div></Wrap></section></Page></>}

function Professional(){return <><DivisionNav type="professional"/><Page label="Healthy Mind Initiatives" title={<>Build a stronger mind. <i>Live a fuller life.</i></>} intro="Professional outreach for individuals, institutions, teams and leaders, grounded in the same framework of mental cultivation."><section className="section sand-bg"><Wrap><div className="grid3">{[['Organizations','Custom training for teams, leadership and high-performance roles.'],['Institutions','Structured attention and mental-development modules for students and educators.'],['Individuals','Personal programs for focus, clarity and greater mental control.']].map(([a,b],i)=><Card key={a}>{i===0?<Building2/>:<GraduationCap/>}<h3>{a}</h3><p>{b}</p><Link to="/contact">Enquire →</Link></Card>)}</div></Wrap></section></Page></>}

function Research(){return <Page label="Research & inquiry" title="Tradition, examined with a contemporary lens." intro="Sustained study of Sāṃkhya, Yoga and Vedic thought alongside contemporary questions around cognition, wellbeing and human development."><section className="section"><Wrap><div className="stats"><div><b>30 years</b><span>Research and study informing the conceptual framework.</span></div><div><b>400+</b><span>Participants in a structured five-session Sandhyā series.</span></div><div><b>India · USA · UK</b><span>Fellowship participation described in the source material.</span></div></div><div className="prose wide"><h2>Academic engagement</h2><p>The source document records a paper selected for presentation at Auro University in February 2026, an abstract selected for a conference at Oxford, and a paper on AI and Self submitted for consideration in Paris.</p></div></Wrap></section></Page>}

const testimonials=[
 ['Participant feedback','The source document includes participant-feedback screenshots from SDS programs. We are keeping this section ready for the approved testimonial wording and names rather than inventing quotations.'],
 ['Practice community','Feedback can be grouped here around practice experience, learning clarity and community participation once the original text is supplied or transcribed.'],
 ['Programs & workshops','A second testimonial group can feature workshop and institutional participants, with consented names, roles and photographs where available.']
]
function Testimonials(){return <Page label="Voices from the community" title="Experiences from practice and learning." intro="A dedicated space for participant voices from SDS practices, fellowships, courses and workshops."><section className="section"><Wrap><div className="grid3">{testimonials.map(([a,b])=><Card key={a}><Quote/><h3>{a}</h3><p>{b}</p></Card>)}</div><p className="note">The DOCX contains feedback as images, but does not provide reliable machine-readable testimonial text. Placeholder copy is intentionally used until the approved wording is available.</p></Wrap></section></Page>}

const teamMembers=[
 {name:'Rounak Maheshwari',role:'Co-founder · Professional practice',initials:'RM',tone:'green',summary:'Chartered Accountant, Certified PU trainer (CIS, USA), and Cognitive Performance and Wellness Coach.',details:'Rounak brings more than 16 years of experience across finance, corporate banking and investment banking. His current work focuses on cognitive stability, attention regulation, stress recovery and inner clarity, while helping develop practical frameworks that connect Indian knowledge systems with contemporary understanding of cognition and attention.'},
 {name:'Anil Arya',role:'CTO · Technology & research',initials:'AA',tone:'green',summary:'Lead software engineer helping make research and writing accessible through digital platforms.',details:'Anil holds a B.Tech in Computer Science and Engineering from Motilal Nehru National Institute of Technology Allahabad, Prayagraj. Alongside technology, his work includes research writing and presentations on consciousness and transformation.'},
 {name:'Dr. Harish Chandra',role:'Inspiration · Scholarship',initials:'HC',tone:'warm',summary:'Scientist and scholar whose work on Sāṃkhya, Yoga Darśana and Pātañjala Upāsanā informs the intellectual foundation.',details:'Dr. Harish Chandra studied engineering at IIT Kanpur and earned a PhD at Princeton University in mathematical simulation of automotive engine combustion. His later work has centered on the study and teaching of meditation philosophy, Sāṃkhya, Yoga Darśana and Pātañjala Upāsanā.'},
]
function Team(){return <Page label="People behind the work" title="Team & inspiration" intro="A multidisciplinary effort connecting research, learning design, community development, technology and India’s knowledge traditions."><section className="section"><Wrap><div className="team-grid expanded">{teamMembers.map(member=><Card key={member.name}><div className={'avatar '+(member.tone==='warm'?'warm':'')}>{member.initials}</div><small>{member.role}</small><h3>{member.name}</h3><p className="team-summary">{member.summary}</p><p className="team-detail">{member.details}</p></Card>)}</div><div className="team-note"><E>Shared body of work</E><p>Rounak’s profile describes SDS as a community platform for the study of Indian knowledge systems and structured Upāsanā practice, and notes his focus on practical, trainable frameworks for cognition, attention and inner clarity.</p></div></Wrap></section></Page>}

function CommunityAbout(){return <SubPage type="community" label="Community · About" title="A sangha for cultivating the mind." intro="SDS is a practitioner community advancing practice, research and study of Upāsanā."><section className="section"><Wrap className="prose wide"><h2>Practice supported by inquiry</h2><p>The community draws from Sāṃkhya, Yoga and Vedic thought while making practices accessible for contemporary life.</p></Wrap></section></SubPage>}
function CommunityPrograms(){return <SubPage type="community" label="Community · Programs" title="Learn through practice, study and fellowship." intro="Programs create structured pathways into Sandhyā, Patanjal Upasana and Sāṃkhya–Yoga learning."><section className="section"><Wrap><div className="grid3"><Card><h3>Sandhyopāsanā</h3><p>Regular community practice.</p></Card><Card><h3>Patanjal Upasana</h3><p>An accessible practice pathway.</p></Card><Card><h3>Sāṃkhya–Yoga Fellowship</h3><p>Weekly conceptual study and inquiry.</p></Card></div></Wrap></section></SubPage>}
function CommunityPractice(){return <SubPage type="community" label="Community · Practice" title="Practice as a lifelong discipline." intro="Explore Sandhyā and Patanjal Upasana as pathways for sustained cultivation of the mind."><section className="section"><Wrap className="prose wide"><h2>Sandhyā and Upāsanā</h2><p>SDS works to revive Sandhyā as a living practice and make Patanjal Upasana accessible to contemporary practitioners.</p></Wrap></section></SubPage>}
function CommunityFellowship(){return <SubPage type="community" label="Community · Fellowship" title="Study Sāṃkhya and Yoga together." intro="A weekly learning environment for deeper conceptual inquiry into Sāṃkhya and Yogadarśana."><section className="section"><Wrap><div className="stats"><div><b>Weekly</b><span>Study and inquiry.</span></div><div><b>Since 2026</b><span>Fellowship described in the source document.</span></div><div><b>Global</b><span>Participation across India, USA and UK.</span></div></div></Wrap></section></SubPage>}
function CommunityResources(){return <SubPage type="community" label="Community · Resources" title="Continue learning." intro="Videos, courses and writing connected with the SDS body of work."><section className="section"><Wrap><div className="grid3"><Card><h3>Quark Wellbeing</h3><a href="https://youtube.com/@quarkwellbeing" target="_blank">YouTube →</a></Card><Card><h3>Darshan Quest</h3><a href="https://youtube.com/@darshan-quest" target="_blank">YouTube →</a></Card><Card><h3>Writing</h3><a href="https://quarkwellbeing.substack.com/" target="_blank">Read the blog →</a></Card></div></Wrap></section></SubPage>}
function ProfessionalAbout(){return <SubPage type="professional" label="Professional · About" title="Mental fitness for contemporary life." intro="Healthy Mind Initiatives extends the SDS framework into professional, educational and individual settings."><section className="section"><Wrap className="prose wide"><h2>A developmental model</h2><p>The initiative frames a healthy mind as a foundation for clarity, resilience, meaningful relationships and human potential.</p></Wrap></section></SubPage>}
function ProfessionalPrograms(){return <SubPage type="professional" label="Professional · Programs" title="Programs built around people and context." intro="Structured pathways for organizations, institutions and individuals."><section className="section"><Wrap><div className="grid3">{[['Organizations','Team and leadership learning.'],['Institutions','Attention and learning modules.'],['Individuals','Focus, clarity and mental control.']].map(([a,b])=><Card key={a}><h3>{a}</h3><p>{b}</p></Card>)}</div></Wrap></section></SubPage>}
function AudiencePage({kind,title,intro}){return <SubPage type="professional" label={'Professional · '+kind} title={title} intro={intro}><section className="section"><Wrap className="prose wide"><h2>Designed for your context</h2><p>We can shape this page further with approved program formats, schedules, outcomes, case studies and enquiry details.</p><Link className="primary inline-cta" to="/contact">Start a conversation <ArrowRight size={16}/></Link></Wrap></section></SubPage>}

function Contact(){return <Page label="Get involved" title="Find the pathway that fits." intro="Join the practitioner community, explore a learning program, or start a conversation about Healthy Mind Initiatives."><section className="section"><Wrap><div className="grid3"><Card><h3>Community</h3><p>Explore practice, learning and fellowship.</p><a href="https://youtube.com/@quarkwellbeing" target="_blank">Explore our work →</a></Card><Card><h3>Organizations</h3><p>Discuss custom training and professional programs.</p><span>Contact details to be added</span></Card><Card><h3>Institutions</h3><p>Explore structured modules for students and educators.</p><span>Contact details to be added</span></Card></div></Wrap></section></Page>}

export default function App(){return <Layout><Routes><Route path="/" element={<Home/>}/><Route path="/approach" element={<Approach/>}/><Route path="/community" element={<Community/>}/><Route path="/community/about" element={<CommunityAbout/>}/><Route path="/community/programs" element={<CommunityPrograms/>}/><Route path="/community/practice" element={<CommunityPractice/>}/><Route path="/community/fellowship" element={<CommunityFellowship/>}/><Route path="/community/resources" element={<CommunityResources/>}/><Route path="/professional" element={<Professional/>}/><Route path="/professional/about" element={<ProfessionalAbout/>}/><Route path="/professional/programs" element={<ProfessionalPrograms/>}/><Route path="/professional/organizations" element={<AudiencePage kind="Organizations" title="Stronger minds at work." intro="Custom learning and training for teams, leadership and high-performance roles."/>}/><Route path="/professional/institutions" element={<AudiencePage kind="Institutions" title="Attention and learning by design." intro="Structured modules for students and educators."/>}/><Route path="/professional/individuals" element={<AudiencePage kind="Individuals" title="Train the mind for everyday life." intro="Personal pathways for focus, clarity and mental control."/>}/><Route path="/research" element={<Research/>}/><Route path="/testimonials" element={<Testimonials/>}/><Route path="/team" element={<Team/>}/><Route path="/contact" element={<Contact/>}/></Routes></Layout>}